package gsrs.stagingarea.model;

import ix.core.models.Indexable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Type;

import javax.persistence.*;
import java.util.Date;
import java.util.UUID;

/**
 * The results of application of Validation (business rules) to a domain entity in the staging area
 */
@Entity
@Table(name = "ix_import_validation", indexes = {@Index(name="idx_ix_import_validation_entity_class_name", columnList = "entity_class_name"),
        @Index(name="idx_ix_import_validation_version", columnList = "version"),
        @Index(name="idx_ix_import_validation_instance_id", columnList = "instance_id")})
/*,
        @Index(name="idx_ix_import_validation_type", columnList = "ValidationType")*/
@Slf4j
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ImportValidation {

    /***
     * category of validation message, mimics what the validation framework does
     */
    public enum ImportValidationType {
        info,
        notice,
        warning,
        error
    }


    /**
     * foreign key to ImportData object
     */
    //maintain backwards compatibility with old GSRS store it as varchar(40) by default hibernate will store uuids as binary
    @Type(type = "uuid-char" )
    @Column(length =40, updatable = false, unique = false)
    @Indexable
    private UUID instanceId;

    /**
     * Set to 1 in all cases.  Use the version value in ImportData (via instanceId) for latest values of version
     */
    @Indexable
    private int version;

    /**
     * Unique, primary key
     */
    @Id
    @GenericGenerator(name = "NullUUIDGenerator", strategy = "ix.ginas.models.generators.NullUUIDGenerator")
    @GeneratedValue(generator = "NullUUIDGenerator")
    //maintain backwards compatibility with old GSRS store it as varchar(40) by default hibernate will store uuids as binary
    @Type(type = "uuid-char" )
    @Column(length =40, updatable = false, unique = true)
    @Indexable
    private UUID ValidationId;

    /**
     * category of validation message, see ImportValidationType enum
     */
    @Indexable
    @Column(length =255, updatable = false, unique = false)
    private ImportValidationType ValidationType;

    /**
     * Message generated by individual validator components. (Each validator applies one or more business rules
     */
    @Indexable
    @Column(length =2048, updatable = false, unique = false)
    private String ValidationMessage;

    /**
     * response from GSRS validation framework
     */
    @Lob
    @Indexable
    private String ValidationJson;

    /**
     * Date this validation was performed and saved
     */
    @Indexable
    private Date ValidationDate;

    /**
     * Not used here
     */
    @Indexable
    @Column(length = 255)
    private String entityClassName;
}
